version: '3'
services:
  frontend:
    build:
      context: ./app  # 前端应用的构建路径，根据实际情况替换为正确的路径
      dockerfile: frontend.Dockerfile   # 指定使用的Dockerfile为Dockerfile.frontend
    ports:
      - "3000:3000"                    # 将容器的 3000 端口映射到宿主机的 3000 端口
  backend:
    build:
      context: ./    # 后端应用的构建路径，根据实际情况替换为正确的路径
      dockerfile: backend.Dockerfile   # 指定使用的Dockerfile为Dockerfile.backend
    ports:
      - "3005:3005"                # 将容器的 3005 端口映射到宿主机的 3005 端口
